### PR TITLE
218 sidebar

### LINKED ISSUE #218: [spike] how to make project page sidebar responsive

### PR DESCRIPTION
**Pull request by jberns**
This PR closes #218 

#### What does this PR do?
This PR adds a responsive sidebar to the 'All Projects' and individual projects pages.

Material-UI Icons was also added to package.json as it was split out from the Material-UI Core package.

### CODE REVIEW

**Comment by eemshi** [comment]
Thanks for moving this feature along! One issue I'm seeing is that the Edit button on the project pages no longer works. Also, it shows the same Github issues for every project even tho I'm pretty sure I previously entered the correct Cfapi project ID for each one. But I can't get in to Edit mode to make sure.

jun-08-2018 15-08-37

**Comment by eemshi** [comment]
@jberns Looking good. One more thought - maybe we should put a heading above the list of projects, "Projects" or "Active Projects" to make it really clear?

**Comment by jberns** [comment]
@eemshi i finished adding a header.  I adjusted the styling a bit to center it because it looked a bit weird while left justified.  I think its because we don't have any Icons or Avatar pictures to indent to the project names.

**Review by eemshi — APPROVED** [review]
🌠

**Pull request merged**
