### PR TITLE
unique email constraint for sign up

### PR DESCRIPTION
**Pull request by sungbae**
This PR closes #[107]

This PR allows unique email sign up. So, this way users will not have separate profiles if they sign in through email vs. quick Google log in.

### CODE REVIEW

**Comment by sungbae** [comment]
Take a look at this issue as I had made a comment about not being able to do this through Auth0.

https://github.com/codefordenver/members/issues/107

**Comment by wdoug** [comment]
What error happens when someone tries to sign up with a different account with the same email?

**Comment by wdoug** [comment]
We'll need to delete @dviramontes' second account before we merge this

**Review by dviramontes — APPROVED** [review]
@sungbae @wdoug I just deleted my second account on members prod. Let's merge this baby! 👍

**Comment by sungbae** [comment]
Sorry didn't reply sooner! There is no error actually. It basically redirects the user back to the dashboard without signing in. I'm probably going to merge in the changes soon. I'll open another issue to make sure there's some kind of error notification when trying to sign up with an existing email. #121

**Comment by dviramontes** [comment]
ok great, thanks @sungbae !

**Pull request merged**
